### ISSUE TITLE
Add `:token` option to be attached into plugin

### ISSUE THREAD

**Issue by aleDsz** [livebook-dev/req_athena#18]
`token` is also know as `AWS Session Token` or `AWS Security Token`

**Comment by josevalim** [comment]
Maybe we should have a select? You can choose between:

* AWS Access Token
* AWS Session / Security Token
* AWS Credentials from machine

**Comment by josevalim** [comment]
It is whatever we have today, but it seems I clearly failed to represent it. :P

**Comment by aleDsz** [comment]
My idea is to allow it to be used from `KinoDB`, but we will override it if they add `:aws_credentials` as a dependency.
But, if they don't want it, just don't add `:aws_credentials` to `Mix.install/1` and we will require it from the Smart Cell.

WDYT?

**Comment by josevalim** [comment]
Hrm... I would prefer it if worked like BigQuery, where if we detect we are inside AWS, it just worked. At best... they would chose something in a select input, instead of having to manually add a dependency. But I am not sure if `aws_credentials` is as easy to use as Goth.

**Comment by aleDsz** [comment]
We can define how we want to check it if we set the env `:credential_providers`.

By default, they will check in order:
- System env/App env
- File system (we can define the "home" path)
- inside AWS ECS
- inside AWS EC2

We can choose a list of providers, and their order, to check the data.
We also can execute the ECS and EC2 directly as we want.
