### ISSUE TITLE
Allow cache to be disabled

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/req_athena#20]
In this case, we need to somehow force a mechanism to compute a new cache. The simplicity of this option will depend if Athena allows us to force a query. If not, we will have to come up with some scheme within Kino.

**Comment by aleDsz** [comment]
If we want to compute a new cache, we need to generate another `ClientRequestToken`, which we do based on query. If we add a checkbox inside the `SQL Cell` to force the Athena query, we should force this token generation, so it would generate another `QueryExecutionId`, caching the result into another file.
