### ISSUE TITLE
Finish aws_credentials support

### ISSUE THREAD

**Issue by wojtekmach** [livebook-dev/req_athena#33]
We're doing Code.ensure_loaded? at runtime which can be very slow: https://github.com/livebook-dev/req_athena/blob/v0.1.4/lib/req_athena.ex#L392.

I believe an easy fix is in that spot to change:

```diff
- Code.ensure_loaded?(:aws_credentials)
+ unquote(Code.ensure_loaded?(:aws_credentials))
```

However there are some other things to consider:

- we should add it as an optional dep: https://github.com/livebook-dev/req_athena/blob/v0.1.4/mix.exs#L46. Since we worked on this it has been published to Hex: https://hex.pm/packages/aws_credentials
- I don't remember if we discussed this at the time but we probably shouldn't configure lib1 from lib2: https://github.com/livebook-dev/req_athena/blob/v0.1.4/lib/req_athena.ex#L407
- maybe we should only ever call this once? https://github.com/livebook-dev/req_athena/blob/v0.1.4/lib/req_athena.ex#L409. For example, we add a ReqAthena.Application and call it there.

**Comment by josevalim** [comment]
If we add aws_credentials as a dependency, both 1 and 3 will be solved.

I guess the `fail_if_unavailable` could be replaced by a try/catch, but it would still log all failed providers on every attempt.

**Comment by josevalim** [comment]
1 and 3 will be solved by making it an optional dependency but `fail_if_unavailable` is tricky because if we don't set it, `aws_credentials` will fail to boot. So we either need to both set it as `runtime: false` in the optional dependency and ask users to either: set it to false or set it as `runtime: false` too (and we continue changing its value).

**Comment by josevalim** [comment]
Btw, fail if unavailable defaults to false, so we can make aws_credentials optional without much concern: https://github.com/aws-beam/aws_credentials/pull/60

**Comment by wojtekmach** [comment]
Awesome, thanks!
